"""Init

Revision ID: 2a8dfbb5147a
Revises: 3f366aaa5900
Create Date: 2023-03-29 19:38:09.899942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8dfbb5147a'
down_revision = '3f366aaa5900'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
