"""Init

Revision ID: 3f366aaa5900
Revises: 624e32f09dc1
Create Date: 2023-03-29 19:26:16.059692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f366aaa5900'
down_revision = '624e32f09dc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
